config/routes.rb
Iguess::Application.routes.draw do

  root :to => "home#index"
  

  resources :mod_configs

  resources :cities

  put "wps_processes/register"
  put "wps_processes/unregister"
  get "wps_processes/process_query"

  resources :wps_servers

  get "datasets/dataset_query"

  put "datasets/del_tag"
  put "datasets/add_data_tag"
  put "datasets/add_data_folder_tag"

  put "dataserver_bookmarks/create"
  put "dataserver_bookmarks/destroy"

  get "/datasets/check_name"

  resources :datasets 

  
  resources :config_datasets
  
  resources :maps

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users
  
  resources :compares

  resources :scenarios
  
  resources :dss

  resources :co2_scenarios do
   member do
    get 'replicate'
    get 'summary'
    get 'overview'
   end
  end
  
  resources :tickets do
    resources :ticket_follow_ups
  end
  

  match "about", :to => "about#index"

  
  get "home/index"
  get "home/geoproxy"
  

  match ":controller(/:action(/:id(.:format)))"
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter {|t| t.set_active_tab("home") }

  def index
    if user_signed_in?
      @user = User.find(current_user.id)
      @current_city  = User.getCurrentCity(current_user, cookies)
      @unapproved_users = User.find_all_by_approved_and_city_id(false, @current_city.id)
    end
  end

  def geoproxy

    require 'net/http'
    require 'timeout'

    rawurl = CGI::unescape(params[:url])
    # needed to build the GetRecordById request. obtained from the ajax call in datasets/index, clicking the gear icon
    id = params[:Id].to_s
    
    
    fixedurl = rawurl.gsub('\\', '%5C')   # Escape backslashes... why oh why???!?

    status = 200
    content_type = 'text/html'
    
    begin
      Timeout::timeout(15) {        # Time, in seconds
        
        if request.get? then
          
          # check if the fixedurl string refers to a CSW request 
          if fixedurl.last(3) == "CSW" then
            
            # then build a full getRecordById request to read a catalogue entry, and return the record xml response
            finalurl = rawurl + "&version=2.0.2&request=GetRecordById&ElementSetName=full&typeNames=gmd:MD_Metadata&outputSchema=http://www.isotc211.org/2005/gmd&Id=" + id
            res = Net::HTTP.get_response(URI.parse(finalurl))
            status = res.code
            content_type = res['content-type']
            @page = res.body
            print @page
            respond_to do |format|
              format.xml { render xml: @page}
            end
          else
            print "GeoProxy sending GET request to: " + String(fixedurl)
            
            res = Net::HTTP.get_response(URI.parse(fixedurl))
            print res.body
  
            status = res.code    # If there was an  error, pass that code back to our caller
            content_type = res['content-type']
   
            # if content_type.include? 'charset=' then
              @page = res.body
            # else
            #   @page = res.body.force_encoding('ISO-8859-1').encode('UTF-8')   # Force the encoding to be UTF-8
            render :layout => false, :status => status, :content_type => content_type
          end
        
        elsif request.post? then
          
          uri = URI(String(fixedurl))
          post = Net::HTTP::Post.new(uri.path + '?' + uri.query)
          post.body = String(request.body.read())
          post.content_type = 'text/xml' 
          
          res = Net::HTTP.start(uri.host, uri.port) do |http|
            http.request(post)
          end
          
          status = res.code    # If there was an  error, pass that code back to our caller
          @page = res.body
          content_type = res['content-type']
          
          render :layout => false, :status => status, :content_type => content_type
        else 
          
          print "GeoProxy couldn't decode request: " + String(fixedurl)
          
        end
        
      }

    rescue Timeout::Error
      @page = "TIMEOUT"
      status = 504    # 504 Gateway Timeout  We're the gateway, we timed out.  Seems logical.
    end

    
  end
end

app/views/home/_ecosystems_about.html.erb
<div class="home-page-text">

  <p>
    Smart City Logistics is based on the open source geospatial software framework iGUESS built on the Open Geospatial Consortium (OGC) Standards. It allows easy and transparent ways of data integration and exchange, the integration and linking of modelling tools and the visualisation of information. iGUESS provides a basis for web based decision support platforms in the fields of Urban logistics, Energy planning, Water management, Air Pollution and Ecosystems Services to make our Cities smarter.
  </p>

  <p>
    For further information on OGC standards please see <a href="http://youtu.be/bfkCdir-yO8">http://youtu.be/bfkCdir-yO8</a>.
  </p>

  <h2>The iGUESS Team</h2>

  <ul>
     <li>  Christian Braun</li>
     <li>  Luís de Sousa</li>
     <li>  Matteo de Stefano</li>
     <li>  Ulrich Leopold</li>
     <li>  Rui Martins</li>
     <li>  Alessio Mastrucci</li>
  </ul>
  <br>
  <i>Former team members and additional contributors</i>
  <ul>
     <li>  Olivier Baume</li>
     <li>  Calin Ciociu</li>
     <li>  Luisa Egenlauf</li>
     <li>  Christopher Eykamp</li>
     <li>  Jovial Matshazi</li>
     <li>  Susanna Salvucci</li>
     <li>  Kerry Schiel</li>
  </ul>
  
  <h2>Contact</h2>
  For more information about the iGUESS project, please contact 
<script type="text/javascript" language="javascript">
<!--
// Email obfuscator script 2.1 by Tim Williams, University of Arizona
// Random encryption key feature by Andrew Moulden, Site Engineering Ltd
// This code is freeware provided these four comment lines remain intact
// A wizard to generate this code is at http://www.jottings.com/obfuscator/
{ coded = "VLGHox.LUZfZLj@LHkO.LV"
  key = "AkUP4iGoq8MESBOdgf3DWFJKYIaHhZzln2ubwjRyTsem5CrcQ1xN0Lt6VpX9v7"
  shift=coded.length
  link=""
  for (i=0; i<coded.length; i++) {
    if (key.indexOf(coded.charAt(i))==-1) {
      ltr = coded.charAt(i)
      link += (ltr)
    }
    else {     
      ltr = (key.indexOf(coded.charAt(i))-shift+key.length) % key.length
      link += (key.charAt(ltr))
    }
  }
document.write("<a href='mailto:"+link+"'>Ulrich Leopold</a>")
}
//-->
</script><noscript>Sorry, you need Javascript on to email me.</noscript>
</div>

app/views/home/_ecosystems_footer.html.erb
<div class="main-text footer">
<table class="footer-table">
  <tr>
    <td>
    	<%= link_to image_tag("list_logo.png", :border => 0, :alt => "Luxembourg Institute of Science and Technology"), "http://www.list.lu/" %>
    </td>
  </tr>
</table>
<div>

app/views/home/_ecosystems_homepage_body.html.erb
   <div class="headline" id="headline1">
      understand your options...
   </div>
   <div class="headline" id="headline2">
      plan your future.
   </div>

   <p id="headline-spacer"></p>

  <div class="main-text">
    
    <a href="<%= maps_path %>"><div class="side-links">Maps Preview</div></a>
    <div class="home-page-text">
    	<p>Smart City Logistics is a decision support platform for urban logistics for European cities. Smart City Logistics provides decision makers with a wide range of easy to understand information to support the development of urban freight transportation plans.</p>

		<p>Addressing urban logistics requires an integrated understanding of transport, environmental and socio-economic aspects to arrive at sustainable solutions. The Smart City Logistics platform maps information on transportation networks, access restrictions, traffic measures, delivery and transport facilities, administrative units, population, land use and emission situations.</p>

		<p>Smart City Logistics allows users to assess trends and relationships from different perspectives and identify innovative and strong sustainable solutions.</p>

		<p>Users will need to register to access the data. Please log in via the link at the top right of this site.</p>
      <br>
      <br>
      <%= link_to image_tag("maps-preview.png", :class=>"map-link-image"), :action => 'index', :controller => 'maps' %>
    </div>
</div>

app/views/home/_hydro-atlas_about.html.erb
<div class="home-page-text">

  <p>
    Smart City Logistics is based on the open source geospatial software framework iGUESS built on the Open Geospatial Consortium (OGC) Standards. It allows easy and transparent ways of data integration and exchange, the integration and linking of modelling tools and the visualisation of information. iGUESS provides a basis for web based decision support platforms in the fields of Urban logistics, Energy planning, Water management, Air Pollution and Ecosystems Services to make our Cities smarter.
  </p>

  <p>
    For further information on OGC standards please see <a href="http://youtu.be/bfkCdir-yO8">http://youtu.be/bfkCdir-yO8</a>.
  </p>

  <h2>The iGUESS Team</h2>

  <ul>
     <li>  Christian Braun</li>
     <li>  Luís de Sousa</li>
     <li>  Matteo de Stefano</li>
     <li>  Ulrich Leopold</li>
     <li>  Rui Martins</li>
     <li>  Alessio Mastrucci</li>
  </ul>
  <br>
  <i>Former team members and additional contributors</i>
  <ul>
     <li>  Olivier Baume</li>
     <li>  Calin Ciociu</li>
     <li>  Luisa Egenlauf</li>
     <li>  Christopher Eykamp</li>
     <li>  Jovial Matshazi</li>
     <li>  Susanna Salvucci</li>
     <li>  Kerry Schiel</li>
  </ul>
  
  <h2>Contact</h2>
  For more information about the iGUESS project, please contact 
<script type="text/javascript" language="javascript">
<!--
// Email obfuscator script 2.1 by Tim Williams, University of Arizona
// Random encryption key feature by Andrew Moulden, Site Engineering Ltd
// This code is freeware provided these four comment lines remain intact
// A wizard to generate this code is at http://www.jottings.com/obfuscator/
{ coded = "VLGHox.LUZfZLj@LHkO.LV"
  key = "AkUP4iGoq8MESBOdgf3DWFJKYIaHhZzln2ubwjRyTsem5CrcQ1xN0Lt6VpX9v7"
  shift=coded.length
  link=""
  for (i=0; i<coded.length; i++) {
    if (key.indexOf(coded.charAt(i))==-1) {
      ltr = coded.charAt(i)
      link += (ltr)
    }
    else {     
      ltr = (key.indexOf(coded.charAt(i))-shift+key.length) % key.length
      link += (key.charAt(ltr))
    }
  }
document.write("<a href='mailto:"+link+"'>Ulrich Leopold</a>")
}
//-->
</script><noscript>Sorry, you need Javascript on to email me.</noscript></div>

app/views/home/_hydro-atlas_homepage_body.html.erb
   <div class="headline" id="headline1">
      understand your options...
   </div>
   <div class="headline" id="headline2">
      plan your future.
   </div>

   <p id="headline-spacer"></p>

  <div class="main-text">
    
    <a href="<%= maps_path %>"><div class="side-links">Maps Preview</div></a>
    <div class="home-page-text">
      <p>Smart City Logistics is a decision support platform for urban logistics for European cities. Smart City Logistics provides decision makers with a wide range of easy to understand information to support the development of urban freight transportation plans.</p>

      <p>Addressing urban logistics requires an integrated understanding of transport, environmental and socio-economic aspects to arrive at sustainable solutions. The Smart City Logistics platform maps information on transportation networks, access restrictions, traffic measures, delivery and transport facilities, administrative units, population, land use and emission situations.</p>


      <p>Smart City Logistics allows to assess trends and relationships from different perspectives and identify innovative and strong sustainable solutions.</p>

      <br>
      <br>
      <%= link_to image_tag("maps-preview.png", :class=>"map-link-image"), :action => 'index', :controller => 'maps' %>
    </div>
</div>

app/views/home/_iguess_footer.html.erb
<div class="main-text footer">
<table class="footer-table">
  <tr>
    <td>
    	<%= link_to image_tag("list_logo.png", :border => 0, :alt => "Luxembourg Institute of Science and Technology"), "http://www.list.lu/" %>
    </td>
    <td class="footer-table-spacer"></td>
    <td>
    	<%= link_to image_tag("music_logo.png", :border => 0, :alt => "MUSIC Project"), "http://themusicproject.eu" %>
    </td>
    <td class="footer-table-spacer"></td>
    <td>
    	<%= link_to image_tag("interreg_logo.png", :border => 0, :alt => "INTERREG IVB"), "http://www.nweurope.eu/" %>
    </td>
  </tr>
</table>
<div>

app/views/home/_lamilo_banner.html.erb
<!-- <div class="owner-logo" style="margin-top: 30px;">
  <%= link_to image_tag("list_logo.png", :border => 0, :size => "99x35", :alt => "Luxembourg Institute of Science and Technology"), "http://www.list.lu/" %>
</div> -->

<!-- <div class="sponsor-logos" style="margin-top: 30px;">
  <%= link_to image_tag("lamilo_logo.png", :border => 1, :alt => "LaMiLo Project"), "http://www.lamiloproject.eu" %>&nbsp;
  <%= link_to image_tag("interreg_logo.png", :border => 0, :alt => "INTERREG IVB"), "http://www.nweurope.eu/" %>
</div> -->

<div>
  <div class="center">
  	<%= link_to image_tag("lamilo_header_image.png", :border => 0, :alt => "Smart City Logistics")%>
  </div>
</div>


<!-- Google Analytics tracking code -->
 <script>
 (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
 })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

 ga('create', 'UA-2000429-9', 'auto');
 ga('send', 'pageview');

 </script>

app/views/home/_lamilo_homepage_body.html.erb
 <div class="main-text"> 
 
   <div class="headline" id="headline1">
      Understand your options...
   </div>
   <div class="headline" id="headline2">
      plan your future.
   </div>

   <p id="headline-spacer"></p>
    
    <a href="<%= maps_path %>"><div class="side-links">Maps Preview</div></a>
    <div class="home-page-text">
		<p>Smart City Logistics is a decision support platform for urban logistics for European cities. Smart City Logistics provides decision makers with a wide range of easy to understand information to support the development of urban freight transportation plans.</p>

		<p>Addressing urban logistics requires an integrated understanding of transport, environmental and socio-economic aspects to arrive at sustainable solutions. The Smart City Logistics platform maps information on transportation networks, access restrictions, traffic measures, delivery and transport facilities, administrative units, population, land use and emission situations.</p>

		<p>Smart City Logistics allows users to assess trends and relationships from different perspectives and identify innovative and strong sustainable solutions.</p>

		<p>Users will need to register to access the data. Please log in via the link at the top right of this site.</p>
		<br>
      <%= link_to image_tag("maps-preview.png", :class=>"map-link-image"), :action => 'index', :controller => 'maps' %>
    </div>
 </div>

app/views/home/_list_about.html.erb
<div class="home-page-text">
  <h2>The iGUESS Team</h2>

  <ul>
     <li>  Christian Braun</li>
     <li>  Luís de Sousa</li>
     <li>  Matteo de Stefano</li>
     <li>  Ulrich Leopold</li>
     <li>  Rui Martins</li>
     <li>  Alessio Mastrucci</li>
  </ul>
  <br>
  <i>Former team members and additional contributors</i>
  <ul>
     <li>  Olivier Baume</li>
     <li>  Calin Ciociu</li>
     <li>  Luisa Egenlauf</li>
     <li>  Christopher Eykamp</li>
     <li>  Jovial Matshazi</li>
     <li>  Susanna Salvucci</li>
     <li>  Kerry Schiel</li>
  </ul>
  
  <h2>Contact</h2>
  For more information about the iGUESS project, please contact 
<script type="text/javascript" language="javascript">
<!--
// Email obfuscator script 2.1 by Tim Williams, University of Arizona
// Random encryption key feature by Andrew Moulden, Site Engineering Ltd
// This code is freeware provided these four comment lines remain intact
// A wizard to generate this code is at http://www.jottings.com/obfuscator/
{ coded = "VLGHox.LUZfZLj@LHkO.LV"
  key = "AkUP4iGoq8MESBOdgf3DWFJKYIaHhZzln2ubwjRyTsem5CrcQ1xN0Lt6VpX9v7"
  shift=coded.length
  link=""
  for (i=0; i<coded.length; i++) {
    if (key.indexOf(coded.charAt(i))==-1) {
      ltr = coded.charAt(i)
      link += (ltr)
    }
    else {     
      ltr = (key.indexOf(coded.charAt(i))-shift+key.length) % key.length
      link += (key.charAt(ltr))
    }
  }
document.write("<a href='mailto:"+link+"'>Ulrich Leopold</a>")
}
//-->
</script><noscript>Sorry, you need Javascript on to email me.</noscript>
</div>

app/views/home/_list_homepage_body.html.erb
   <div class="headline" id="headline1">
      understand your options...
   </div>
   <div class="headline" id="headline2">
      plan your future.
   </div>

   <p id="headline-spacer"></p>

  <div id="front-page-tabs">
         <div class="tabs">
         <ul class="dosomething">
            <li><a href="#">View Some Data</a></li>
            <li><a href="#">Run Calculation Module</a></li>
            <li><a href="#">Check Running Module</a></li>
         </ul>
      </div>

      <!-- tab "panes" -->
      <div class="panes">
         <div class="front-page-tab-body" id="view-some-data">
            View your data or register new datasets
            <p class="intro">iGUESS can show you any registered dataset on an interactive map of your city.</p>
            <div class="inner-content">
               <p><%= link_to "Explore maps of my city", :controller => 'maps'%></p>
               <p><%= link_to "See my datasets", :controller => 'datasets'%></p>
               <p><%= link_to "Register new data", :controller => 'datasets', :action => 'mass_import', :id => 1 %></p>
            </div>
         </div>
         <div class="front-page-tab-body" id="run-a-module">
            Configure and run a calculation module
            <p class="intro">The module catalog shows the calculations that iGUESS can perform.</p>
            <div class="inner-content">
               <p><%= link_to "View module catalog", :controller => 'mod_configs', :anchor => 'module_catalog_tab'%></p>
            </div>
         </div>
         <div class="front-page-tab-body" id="check-module">
            Check on the status of a running module
            <p class="intro">Logged in users can view the status of modules being run at their city.</p>
            <div class="inner-content">
               <p><%= link_to "See running modules", :controller => 'mod_configs'%></p>
            </div>            
         </div>
      </div>
</div>

<div class="clear"></div>

<script type="text/javascript">  // Activate the tabs with jquerytools>tabs
  // perform JavaScript after the document is scriptable.
  $(function() {
      // setup ul.tabs to work as tabs for each div directly under div.panes
      $("ul.dosomething").tabs("div.panes > div");
  });
</script>

app/views/home/_smartcitylog-agadir_banner.html.erb
<!-- <div class="owner-logo" style="margin-top: 30px;">
  <%= link_to image_tag("list_logo.png", :border => 0, :size => "99x35", :alt => "Luxembourg Institute of Science and Technology"), "http://www.list.lu/" %>
</div> -->

<!-- <div class="sponsor-logos" style="margin-top: 30px;">
  <%= link_to image_tag("lamilo_logo.png", :border => 1, :alt => "LaMiLo Project"), "http://www.lamiloproject.eu" %>&nbsp;
  <%= link_to image_tag("interreg_logo.png", :border => 0, :alt => "INTERREG IVB"), "http://www.nweurope.eu/" %>
</div> -->

<div>
  <div class="center">
  	<%= link_to image_tag("lamilo_header_image.png", :border => 0, :alt => "Smart City Logistics")%>
  </div>
</div>


<!-- Google Analytics tracking code -->
 <script>
 (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
 })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

 ga('create', 'UA-2000429-9', 'auto');
 ga('send', 'pageview');

 </script>

app/views/home/_smartcitylog-agadir_footer.html.erb
<div class="main-text footer">

<table class="footer-table">
  <tr>
    <td rowspan=2>
    </td>
    <td align="left" valign="bottom">
    <%= link_to image_tag("list_logo.png", :border => 0, :alt => "Luxembourg Institute of Science and Technology"), "http://www.list.lu/" %>
    </td>
    <td>
      <div class="module-surround">
        <div class="module-title">
          <h2 class="footer-title">About LIST</h2>
        </div>
        <div class="module-content">
          <ul class="footer-menu">
            <li>
              <a title="LIST Website" href="http://www.list.lu/" target="_blank"><span>LIST Website</span></a>
            </li>
          </ul>
        </div>
      </div>
    </td>
    <td rowspan=2>
    </td>
  </tr>
  <tr>
  	<td colspan=2 align=center>
  		<span>&#xa9; 2014-2015 Luxembourg Institute of Science and Technology | </span>
  		<a title="Legal Info" href="/legal"><span>Legal Info</span></a>
  	</td>
  </tr>
</table>
<div>

app/views/home/geoproxy.html.erb
<%= raw @page %>

app/views/home/index.html.erb
<!-- Show a list of users pending approval -->
<% if user_signed_in? and @user.is_admin and @unapproved_users.length > 0%>
  <table class="zebra">
    <tr><th colspan=2 class="center"><%= @current_city.name %> users waiting for approval</th></tr>
    <% @unapproved_users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to "Edit", edit_user_path(user) %></td>
      </tr>
    <% end %>
  </table>
<% end %>

<%= render @site_details.body_html_file %>