config/routes.rb
Iguess::Application.routes.draw do

  root :to => "home#index"
  

  resources :mod_configs

  resources :cities

  put "wps_processes/register"
  put "wps_processes/unregister"
  get "wps_processes/process_query"

  resources :wps_servers

  get "datasets/dataset_query"

  put "datasets/del_tag"
  put "datasets/add_data_tag"
  put "datasets/add_data_folder_tag"

  put "dataserver_bookmarks/create"
  put "dataserver_bookmarks/destroy"

  get "/datasets/check_name"

  resources :datasets 

  
  resources :config_datasets
  
  resources :maps

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users
  
  resources :compares

  resources :scenarios
  
  resources :dss

  resources :co2_scenarios do
   member do
    get 'replicate'
    get 'summary'
    get 'overview'
   end
  end
  
  resources :tickets do
    resources :ticket_follow_ups
  end
  

  match "about", :to => "about#index"

  
  get "home/index"
  get "home/geoproxy"
  

  match ":controller(/:action(/:id(.:format)))"
  
end

app/models/mod_config.rb
class ModConfig < ActiveRecord::Base
   belongs_to :wps_server
   belongs_to :city
   belongs_to :wps_process
   belongs_to :run_status

     
   has_many :datasets, :through => :config_datasets
   has_many :config_datasets, :dependent => :destroy

   has_many :config_text_inputs, :dependent => :destroy    # :dependent => :destroy deletes text entries when we delete a config
   # accepts_nested_attributes_for :config_text_inputs       # This lets us update config_text_inputs when updating the ModConfig 
end

app/controllers/mod_configs_controller.rb
class ModConfigsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]
  before_filter {|t| t.set_active_tab("modules") }

  # GET /mod_configs
  # GET /mod_configs.json

  respond_to :html, :js


  def index
    @current_city = User.getCurrentCity(current_user, cookies)
    @mod_configs  = ModConfig.find_all_by_city_id(@current_city.id)

    # Select the processes to show in the Module Catalog.  If you are logged in, you will see only modules
    # registered for your city.  If you are not logged in, you will see modules registered to all cities in your
    # instance (i.e. Lamilo or iGUESS).
    if user_signed_in?    # Get all servers associated with this city
      @wps_processes = WpsProcess.joins(:wps_server)
                                 .where('city_id' => @current_city.id, :alive => true)
                                 .order('title, identifier')   # For catalog

      @wps_servers   = WpsServer.find_all_by_city_id_and_alive(@current_city.id, true)

    else    # User not signed in -- get all servers for all cities attached to this instance

      @wps_processes = WpsProcess.joins(:wps_server, {:wps_server => :city})
                                 .where(:cities => {:site_details_id => @site_details.id })
                                 .where(:alive => true)
                                 .order('title, identifier')
                                 .uniq_by{|s| s.wps_server.url + s.identifier }

      # Make a list of the servers associated with the processes we selected.
      # Have to do this this way due to denormalization of wps_servers table.
      @wps_servers = @wps_processes.map{|p| p.wps_server }.uniq_by{|p| p.id }
    end                               

    respond_to do |format|
      format.html # index.html.erb
    end
  end


  def showError(msg)
    flash[:error] = msg

    respond_to do |format|
      format.html { redirect_to mod_configs_url }
    end
  end


  # GET /mod_configs/1
  # GET /mod_configs/1.json
  def show
    @mod_config = ModConfig.find(params[:id])

    @current_city = User.getCurrentCity(current_user, cookies)

    if @mod_config.city_id != @current_city.id 
      showError("Cannot view that module with the currently selected city.  Sorry!")
      return
    end

    if not User.canAccessObject(current_user, @mod_config)
      showError("Insufficient permissions -- you cannot access this object!")
      return
    end

    # current_user should always be set here
    @datasets        = Dataset.find_all_by_city_id(@current_city.id)
   
    # Protect against database corruption; if a dataset is deleted from the datasets table and not
    # removed from config_datasets, the if-then clause in the map statement will give protection
    @datasetValues   = ConfigDataset.find_all_by_mod_config_id(params[:id])
                                    .map{|d| if d.dataset then 
                                                "'" + d.id.to_s + ":" + d.input_identifier + 
                                                "'" + ': "' + d.dataset.id.to_s + '"' 
                                            end }
                                    .join(',')

    # Note that some inputs have been known to begin with problematic chars like "-"      
    n = -1                
    @textInputValues = ConfigTextInput.find_all_by_mod_config_id(@mod_config)
                                      .map{|t| "'" + t.id.to_s + ":" + t.identifier + 
                                        (t.is_input ? 'input' : 'output') + "'" + ': "' + t.value + '"' }
                                      .join(',')
                                      
    #@text_input_params  = @mod_config.wps_process.process_params.find_all_by_is_input(true, :order=>:title)
    #@text_input_params  = @mod_config.wps_process.process_params.Topic.find(:all, :conditions => ['datatype not equal (?)', ])
    @text_input_params  = @mod_config.wps_process.process_params.where("datatype != 'ComplexData' AND is_input IS TRUE", :order=>:title)
    @complex_input_params  = @mod_config.wps_process.process_params.find_all_by_is_input_and_datatype(true, "ComplexData", :order=>:title)
    @output_params = @mod_config.wps_process.process_params.find_all_by_is_input(false, :order=>:title)
    
    #binding.pry

    respond_to do |format|
      format.html # show.html.erb
    end
  end


  # GET /mod_configs/new
  # GET /mod_configs/new.json
  def new
    if not user_signed_in?    # Should always be true
      showError("Insufficient permissions -- you are not logged in!")
      return
    end

    # current_user should always be set here
    @current_city = User.getCurrentCity(current_user, cookies)

    @mod_config = ModConfig.new
    @wps_servers = WpsServer.find_all_by_alive(:true)

    @wps_processes = WpsProcess.joins(:wps_server)
                               .where('wps_servers.city_id' => @current_city.id, :alive => :true)
                               .order('title, identifier')   # For catalog
    @datasets = Dataset.all

    @textinputs = [ ]
    
    #binding.pry

    respond_to do |format|
      format.html
    end
  end


  ReadyCode     = RunStatus.find_by_status('READY').id
  NeedsDataCode = RunStatus.find_by_status('NEEDS_DATA').id
  ErrorCode     = RunStatus.find_by_status('ERROR').id
  RunningCode   = RunStatus.find_by_status('RUNNING').id

  # NOTE that this is not a definitve status -- we don't know, for example, which datasets are needed, and whether they
  # have been provided.  This really just detects that there are blank text items.  This function should probably be removed.
  def getStatus(mod_config)

    id = mod_config.id.to_s

    # This beast figures out if there are any missing inputs or outputs for the specified module.  Note that 
    # the most recent status of the module must be saved for this to work!
    sql = "
      WITH missing AS (
        SELECT COUNT(*) AS c 
        FROM iguess_dev.mod_configs AS mc 
        LEFT JOIN iguess_dev.process_params     AS pp  ON mc.wps_process_id = pp.wps_process_id
        LEFT JOIN iguess_dev.config_datasets    AS cd  ON pp.identifier = cd.input_identifier AND cd.mod_config_id = mc.id
        LEFT JOIN iguess_dev.config_text_inputs AS cti ON pp.identifier = cti.identifier AND cti.mod_config_id = mc.id
        WHERE mc.id = " + id + " AND pp.alive = TRUE AND pp.is_input = TRUE AND cd.dataset_id IS NULL AND (cti.value IS NULL OR cti.value = '')
      ) 

      SELECT sum(c) FROM missing
    "

    connection = ActiveRecord::Base.connection
    connection.execute(sql) 

    results = ModConfig.find_by_sql sql
    errs = results[0]["sum"]

    return errs == "0" ? ReadyCode : NeedsDataCode
  end


  # Only called via ajax request... All we need to do is set status in the database to stop
  def stop_running
    @mod_config = ModConfig.find(params[:id])

    if not User.canAccessObject(current_user, @mod_config)
      return
    end

    @mod_config.status = ReadyCode
    @mod_config.run_status_id = ReadyCode
    @mod_config.save

    respond_with do |format|
      format.js { render :json => @mod_config.to_json(:include => :run_status), :status => :ok }
    end
  end



  # Build the cmd line that we need to launch wpsstart.py
  def assembleCommandLine(mod_config, inputs, outputFields, outputTitles)

    cmd = 'cd ' + Rails.root.to_s() + '; ' + PythonPath + ' wpsstart.py ' 
    cmd += '--url="'      + mod_config.wps_process.wps_server.url + '" ' 
    cmd += '--procname="' + mod_config.wps_process.identifier     + '" '
    cmd += '--inputs="['  + inputs.map { |i| i.to_s }.join(",")   + ']" '

    argOutputs = '--outputs="{'
    j = 0
    until j == outputFields.size
      if (j > 0) 
        argOutputs += ", "
      end
      argOutputs += "'" + outputFields[j] + "':'" + outputTitles[j] + "'"
      j += 1
    end
    argOutputs += '}"'


    cmd += argOutputs 

    return cmd
  end



  # Only called via ajax request... need to fire up WPSClient and tell it to start
  # running the specified module
  def run
    @mod_config = ModConfig.find(params[:id])
    
    if not User.canAccessObject(current_user, @mod_config)
      return
    end

    require 'uri'

    inputs       = []
    outputFields = []
    outputTitles = []

    @aoi = nil

    if @mod_config.aoi != -1 then
      @aoi = Dataset.find_by_id(@mod_config.aoi)
    end

    @current_city = User.getCurrentCity(current_user, cookies)


    # These identifiers are the ones that are still "active".  The database does not store parameters
    # that are not "alive", so this list will be current as of last harvester run.  To be clear, there
    # may be come values in config_text_inputs that are associated with @mod_config that are not currently
    # in use... we want those in case a wps parameter reappears in the future (peraps someone was doing 
    # maintenance, and temporarily removed a parameter; we don't want to corrupt all our configurations 
    # by deleting the user's selected inputs).
    activeParamIdentifiers = @mod_config.wps_process.process_params.map { |p| p.identifier }


    @mod_config.datasets.map { |dataset| 
      dataRequest = dataset.getRequest(@current_city.srs, @aoi)

      configDataset = ConfigDataset.find_by_mod_config_id_and_dataset_id(@mod_config.id, dataset.id) 

      inputs.push("('" + configDataset.input_identifier + "', '" + dataRequest + "')")
    }

    # Text fields -- both inputs and outputs; only use fields that are still active
    @mod_config.config_text_inputs.keep_if{ |c| activeParamIdentifiers.include?(c.identifier) }.map { |d|  
          if d.is_input then 
            inputs.push("('" + d.identifier + "', '" + d.value.gsub("&", "&amp;") + "')")
          else
            outputFields.push(d.identifier)
            outputTitles.push(d.value)
          end
    }

    # Assemble our command line
    cmd = assembleCommandLine(@mod_config, inputs, outputFields, outputTitles)

app/views/mod_configs/_show_area_of_interest_control.erb
<div id="above-area-of-interest-spacer"></div>
<label class="simple_form label" id="area-of-interest-label">Area of Interest</label>

<% aois = getAoiDatasets(@current_city) %>      <%# There will always be at least one %>
<% if aois.size == 1 then %>
    There are no datasets tagged with "Area of Interest"
<% else %>
    <!-- This item will get an id of "mod_config_aoi" -->
    <%= collection_select(:mod_config, :aoi, aois, :id, :title, {}, {:class=>"disableable", :onchange=>"onSelectedDatasetChanged()"} ) %>
<% end %>

app/views/mod_configs/index.html.erb
<h1 class="page_header">Modules</h1>

<div class="explanation">
  <% if user_signed_in? %>
    <% if @wps_servers.length > 0 %>
      <ul>
        <li>Users can create Module Configurations from a Module Template by specifying all inputs and outputs that template requires.</li>
        <li>A list of Module Templates can be found in the Module Catalog.</li>
      </ul>
    <% else %>
      <ul>
        <li>Before you can start working with modules, you need to add a WPS server using the link below.</li>
      </ul>
    <% end %>
  <% else %>
    Registered users can create Module Configurations based on processes available on various remote web servers.  The Catalog below shows some of the modules that other users of iGUESS are using.
  <% end %>
</div>


<ul class="tabs">
  <% if user_signed_in? %>
    <li><a class="l" id="t1" href="#configured_modules_tab">Configured Modules</a></li>
  <% end %>
  <li><a class="l" id="t2" href="#module_catalog_tab">Module Catalog</a></li>
</ul>


<div id="tab-panes" class="tab-pane-container">
  <% if user_signed_in? %>
    <div id="configured_modules_tab">
      <% if @wps_servers.empty? %>
        No process servers have been configured.  You can add one by clicking on the link below.<br>
      <% else %>
        <% if @mod_configs.empty? %>
          <div id="mod-list-none">
            <% if user_signed_in? %>
              The Module Catalog is empty for <span class="city-name"><%= @current_city.name %></span>.  
              <%= link_to "Click here to create a new configuration.", new_mod_config_path %>
            <% else %>
              The Module Catalog is currently empty.
            <% end %>
          </div>   
        <% else %>
          <div id="mod-list">      
            These are the calculation modules that have been configured.

            <table id="sortable_table" class="zebra sortable">
              <thead><tr><th>Name</th><th>Based on</th><th>Status</th><th>Notes</th></tr></thead>
              <tbody id="tableContainer">
                <% @mod_configs.each do |m| %> 
                  <% ok = (m.wps_process && m.wps_process.alive) %>
                  <tr> 
                    <td>
                      <% if ok %>
                        <%= link_to(m.name, m) %>
                      <% else %>
                        <%= m.name %>
                        <div class="error-msg module-not-found">Process not found on server -- It is either offline or has been deleted or renamed</div>
                        <%= link_to m, 
                                    :method => :delete,
                                    :confirm => "Deleting this configuration is a permanent action.\n\n" +
                                             "Click OK if you are sure you want to delete this configuration." do %>
                          <%= image_tag("document_delete_16.png", :class => "link-icon") %>Delete Configuration
                        <% end %>
                      <% end %>
                    </td>
                    <td><%= m.wps_process && (m.wps_process.title || m.wps_process.identifier) || "Unknown process" %></td>
                    <td><span class="status-<%= m.run_status.status %>"><%= m.run_status.pretty_name %></span></td>
                    <td><%= m.descr %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% end %>
        <br />
        <%= link_to new_mod_config_path do %>
          <%= image_tag("document_add_24.png", :class => "link-icon", :title=> "Create a new module configuration") %>New Module Configuration
        <% end %>
      <% end %>
    </div>
  <% end %>

  <div id="module_catalog_tab">
     
    <% if @wps_servers.length == 0 %>
      No process servers have been configured.  You can add one by clicking on the link below.
    <% else %>
      <div id="module-catalog">
        <% @wps_processes.each do |p| %>
          <h2 class="process-title"><%= p.title %></h2>
          <div class="catalog-item">
            <div class = "process-identifier">Identifier: <span><%= p.identifier %></span></div>
            <div class="process-descr"><%= p.abstract %></div>
            <div class="process-server-name">
              <span class="hosted-by">Hosted by:</span>
              <span class="server-name"><%= p.wps_server.title %></span>
              <span class="info-icon properties" title="Click for details" 
                    rel="#server-infotable-<%= p.wps_server.id %>"></span>
            </div>

            <!-- Inputs and outputs -->
            <table class="model-descr-table">
              <% inputs  = ProcessParam.find_all_by_wps_process_id_and_is_input_and_alive(p.id, true,  true, :order=>:title) %>
              <% outputs = ProcessParam.find_all_by_wps_process_id_and_is_input_and_alive(p.id, false, true, :order=>:title) %>

              <tbody class="inputs">
                <tr><th colspan=3 class="group-header" scope="rowgroup"><div class="outdent">
                  <% if inputs.size == 0 %>
                      No Inputs
                  <% else %>
                    Model Inputs
                  <% end %>
                </div></th></tr>
                
                <% if inputs.size > 0 %>
                  <tr><th>Parameter Name</th><th>Identifier</th><th>Description</th></tr>

                  <% inputs.each do |i| %>
                    <tr>
                      <td class="param-name"><%= i.title %></td>
                      <td class="param-name">[<%= i.identifier %>]</td>
                      <td class="param-descr"><%= i.abstract %></td>
                    </tr>
                  <% end %>
                <% end %>

                <tr><th colspan=3 class="group-header" scope="rowgroup"><div class="outdent">
                  <% if outputs.size == 0 %>
                      No Outputs
                  <% else %>
                    Model Outputs
                  <% end %>
                </div></th></tr>

                <% if outputs.size > 0 %>
                  <tr><th>Parameter Name</th><th>Identifier</th><th>Description</th></tr>

                  <% outputs.each do |o| %>
                    <tr>
                      <td class="param-name"><%= o.title %></td>
                      <td class="param-name">[<%= o.identifier %>]</td>
                      <td class="param-descr"><%= o.abstract %></td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>

            <% if user_signed_in? %>
              <a href="/mod_configs/new?template=<%= p.id %>">
                <%= image_tag("document_add_24.png", :class => "link-icon") %>Create new configuration for this service</a>
            <% end %>
          </div>  <!-- End of "catalog-item" div -->
        <% end %>
      <% end %>
    </div>  <!-- End of "module-catalog" div-->
  </div> <!-- End of "module_catalog_tab" div -->

  <% if user_signed_in? %>
    <%= link_to "Register New Modules", new_wps_server_path, :title => "register new modules from WPS servers" %>
  <% end %>

  <!-- The following will start life hidden, and will only be revealed when the user clicks an info button -->
  <!-- Details (name, descr, etc.) will be populated as we get info from the servers -->
  <% @wps_servers.each do |s| %>
    <div class="infotable" id="server-infotable-<%= s.id %>">
      <div class="close"></div>
      <h1  class="wps-title"><%= s.title %></h1>
      <div class="wps-abstr"><%= s.abstract %></div>
      <div style="overflow:hidden">
        <dl>
          <dt>Provider:</dt><dd class="wps-providerName"><%= s.provider_name %></dd>
          <dt>Contact:</dt><dd>
            <span class="wps-email">
              <%= mail_to(s.contact_email, s.contact_name, :encode => :javascript) %>
            </span>
          </dd>
          <dt>Server URL:</dt><dd><%= s.url %></dd>
          <dt>GetCapabilities URL:</dt><dd class="wps-describeProcessLink">
            <%= link_to("WPS", s.url + "?SERVICE=WPS&VERSION=1.1.0&REQUEST=GetCapabilities", :target => "_blank") %>
          </dd>
        </dl>
      </div>
    </div>
  <% end %>
</div>  

<script>
  // Gets run when page is fully loaded
  $(document).ready(function() 
  {
    // Activate our jquery tabs 
    if($("ul.tabs").length != 0) {
      $(function() {
        // setup ul.tabs to work as tabs for each div directly under div.panes
        $('ul.tabs').tabs('#tab-panes > div', { history: true });
      });
    }

    $('span[rel]').overlay(); 

    for(var i = 0; i < <%= @wps_processes.size %>; i++)
      $('.item-' + i + ' span[rel]').overlay();    // Activate layer info overlays

    initializeAccordion('#module-catalog > h2', '.catalog-item');


    $('#sortable_table').tablesorter({ sortList: [[0,0]], headers: { 3: {sorter: false}}, sortMultiSortKey: 'ctrlKey' });   
  });
</script>

app/views/mod_configs/new.html.erb
<h1 class="page_header">Configure a Module</h1>

<div class="explanation">
  You are configuring a new module.  Provide a unique name, a description, and specify any datasets you can.
  You will have a chance to provide any missing data for this module in subsequent steps.
</div>


<%= simple_form_for @mod_config, :validate => true do |f| %>
  <%= f.error_notification %>

  <%= f.input :name, :as => :string, :placeholder => 'Configuration name' %>

  <div class="input text">
    <label class="simple_form label">Module Type</label>
    <span>
      <select class="process-dropdown-control" id="processControl">
        <%= options_for_select(@wps_processes.map{|p| [p.title, p.id] }, 
                               { :selected => params[:template] }) %>
      </select>
    </span>
  </div>
  <div class="input text"><label class="simple_form label"></label><span id="proc-descr">&nbsp;</span></div>


  <%= f.input :descr, :as => :text, :label => "Description", 
              :input_html => { :rows => 6, :cols => 80, :maxlength => 5000 },
              :placeholder => "Description of configuration" %>

  <%# NOTE -- We don't have a configuration here when we are creating a new module! %>
  <div id="input-output-form">   
    <%= render :partial => "show_area_of_interest_control" %>

    <label class="simple_form label table-label">Inputs</label>
    <table class="zebra" id="input-table"> <!-- Will be populated via script --></table>
    <label class="simple_form label table-label">Outputs</label>
    <table class='zebra' id="output-table"><!-- Will be populated via script --></table>

    <%= render :partial => "show_associated_parameters_table",
               :locals  => { :mode => :input,  :config => @mod_config } %>

    <%= render :partial => "show_associated_parameters_table",
               :locals  => { :mode => :output, :config => @mod_config } %>
  </div>

  <div id="bottom-links">
    <%# Add a cancel link that gets back to the different places we could have come from %>
    <% came_from = params[:came_from] || "" %>

    <% if came_from == "catalog" %>
      <%= link_to "Cancel", mod_configs_path(:anchor => :module_catalog_tab) %>
    <% else %>
      <%= link_to "Cancel", mod_configs_path %>
    <% end %> 

    <input type="hidden" name="wps_process_id" id="wps_process_id">

    <%= f.submit "Create New Configuration" %>
  </div>

<% end %>



<script>

  // User has selected a different process from the drop down box... need to rebuild inputs/outputs sections
  var onProcessChanged = function()
  {
    // These functions are defined in _show_assocated_parameters_table.erb
    populateTable(Procs[$('#processControl').val()].inputs,  true);
    populateTable(Procs[$('#processControl').val()].outputs, false);

    var identifier   = Procs[$('#processControl').val()].identifier;

    $("#wps_process_id").val(Procs[$('#processControl').val()].id);

    // Set the description field
    $("#proc-descr").html(Procs[$('#processControl').val()].descr || '&nbsp');
  };



  var serverProcessingComplete  = false;  // True when we have all the dataset info we expect


  // This will be a javascript struct that holds info about the various processes we can run, indexed by the database id
  var Procs = { };

  <% @wps_processes.each do |p| %> 
    Procs[<%= p.id %>] = {
      identifier: "<%= escape_javascript(p.identifier) %>",
      id:         <%= p.id %>,
      title:      "<%= escape_javascript(p.title || p.identifier) %>",
      descr:      "<%= escape_javascript(p.abstract) %>",
      serverUrl:  "<%= escape_javascript(p.wps_server.url) %>",
      inputs:     [
        <% ProcessParam.find_all_by_wps_process_id_and_is_input_and_alive(p.id, true, true, :order=>:title).each { |x| %>
          <%= raw x.to_json + ',' %><% } 
        %>],
      outputs:    [
        <% ProcessParam.find_all_by_wps_process_id_and_is_input_and_alive(p.id, false, true, :order=>:title).each { |x| %>
          <%= raw x.to_json + ',' %><% } 
        %>]
    };
  <% end %>


  // Called when we've gotten whatever response we're going to get from a wfs server -- here type will always be 'WFS'
  // This will be called once for every server we probe

  // User has updated an input or output entry slot (called via onChange event)
  // In this case, we have nothing to do
  var onInputOutputTextEntryChanged = function(field) 
  { 
    checkIfNameIsAvailable(field);
  }

  // Here a dataset dropdown has changed.  Again we have nothing to do.
  var onSelectedDatasetChanged = function() { }

  // Gets run after a form field gets updated
  function readyToRunModule() { }



  $(document).ready(function () {
    $("#processControl").change(function() {
      onProcessChanged();
    });

    onProcessChanged();   // Build initial form configuration
  });
  
</script>